name = "tauri-update-server"
workers_dev = true
compatibility_date = "2024-12-22"
main = "src/index.ts"

[vars]
GITHUB_ACCOUNT = 'xiehuqiqi'
GITHUB_REPO = 'yufox-workspace'
GITHUB_TOKEN = '' # Optional - used with private repos

[build]
command = "npm install && npm run build"
